---
title: "104 P.ret"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)

g <- read_excel("~/Documents/Experiments/10.23.25 P.ret.xlsx", 
    sheet = "Lum")
h <- read_excel("~/Documents/Experiments/10.23.25 P.ret.xlsx", 
    sheet = "OD")
i <- read_excel("~/Documents/Experiments/10.23.25 P.ret.xlsx", 
    sheet = "Lum OD")

```

```{r GFP}

colors <- c("102-0.1" = "seagreen","102-1" = "pink", "104-0.1" = "orange", "104-1" = "lightblue")

p1 <- ggplot(g, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102-1"),linewidth=1) +
  geom_line(aes(y = C1, color="102-1"),linewidth=1) +
  geom_line(aes(y = E1, color="102-1"),linewidth=1) +
  geom_line(aes(y = G1, color="102-1"),linewidth=1) +
  geom_line(aes(y = A3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = C3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = E3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = G3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = A5, color="104-1"),linewidth=1) +
  geom_line(aes(y = C5, color="104-1"),linewidth=1) +
  geom_line(aes(y = E5, color="104-1"),linewidth=1) +
  geom_line(aes(y = G5, color="104-1"),linewidth=1) +
  geom_line(aes(y = A7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = C7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = E7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = G7, color="104-0.1"),linewidth=1) +
   labs(title=" P.ret iLUX Lum",
        x ="Time (hours)", y = "Lum (AU)",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("104Lum.png") 

p1 <- ggplot(h, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102-1"),linewidth=1) +
  geom_line(aes(y = C1, color="102-1"),linewidth=1) +
  geom_line(aes(y = E1, color="102-1"),linewidth=1) +
  geom_line(aes(y = G1, color="102-1"),linewidth=1) +
  geom_line(aes(y = A3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = C3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = E3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = G3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = A5, color="104-1"),linewidth=1) +
  geom_line(aes(y = C5, color="104-1"),linewidth=1) +
  geom_line(aes(y = E5, color="104-1"),linewidth=1) +
  geom_line(aes(y = G5, color="104-1"),linewidth=1) +
  geom_line(aes(y = A7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = C7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = E7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = G7, color="104-0.1"),linewidth=1) +
  scale_y_log10()+
   labs(title="P.ret iLUX OD",
        x ="Time (hours)", y = "Log OD",
         color = "Legend") +
    scale_color_manual(values = colors)
  p1
#ggsave("104OD.png")
  

```

```{r OVL}
colors <- c("102-0.1" = "seagreen","102-1" = "pink", "104-0.1" = "orange", "104-1" = "lightblue")

r<- ggplot()+ 
  geom_point(data = data.frame(x = h$A1, y = g$A1), aes(x = x, y = y, color="102-1"))+
  geom_point(data = data.frame(x = h$C1, y = g$C1), aes(x = x, y = y, color="102-1"))+
  geom_point(data = data.frame(x = h$E1, y = g$E1), aes(x = x, y = y, color="102-1"))+
  geom_point(data = data.frame(x = h$G1, y = g$G1), aes(x = x, y = y, color="102-1"))+  
  geom_point(data = data.frame(x = h$A3, y = g$A3), aes(x = x, y = y, color="102-0.1"))+
  geom_point(data = data.frame(x = h$C3, y = g$C3), aes(x = x, y = y, color="102-0.1"))+
  geom_point(data = data.frame(x = h$E3, y = g$E3), aes(x = x, y = y, color="102-0.1"))+
  geom_point(data = data.frame(x = h$G3, y = g$G3), aes(x = x, y = y, color="102-0.1"))+
  geom_point(data = data.frame(x = h$A5, y = g$A5), aes(x = x, y = y, color="104-1"))+
  geom_point(data = data.frame(x = h$C5, y = g$C5), aes(x = x, y = y, color="104-1"))+
  geom_point(data = data.frame(x = h$E5, y = g$E5), aes(x = x, y = y, color="104-1"))+
  geom_point(data = data.frame(x = h$G5, y = g$G5), aes(x = x, y = y, color="104-1"))+
  geom_point(data = data.frame(x = h$A7, y = g$A7), aes(x = x, y = y, color="104-0.1"))+ 
  geom_point(data = data.frame(x = h$C7, y = g$C7), aes(x = x, y = y, color="104-0.1"))+
  geom_point(data = data.frame(x = h$E7, y = g$E7), aes(x = x, y = y, color="104-0.1"))+ 
  geom_point(data = data.frame(x = h$G7, y = g$G7), aes(x = x, y = y, color="104-0.1"))+
 labs(title="P.ret iLUX OVL",
        x ="Optical Density", y = "GFP (AU)", color = "Legend") +
    scale_color_manual(values = colors)
r

#ggsave("104OVL.png")

```

```{r}
p1 <- ggplot(i, aes(x=Hours)) + 
  geom_line(aes(y = A1, color="102-1"),linewidth=1) +
  geom_line(aes(y = C1, color="102-1"),linewidth=1) +
  geom_line(aes(y = E1, color="102-1"),linewidth=1) +
  geom_line(aes(y = G1, color="102-1"),linewidth=1) +
  geom_line(aes(y = A3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = C3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = E3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = G3, color="102-0.1"),linewidth=1) +
  geom_line(aes(y = A5, color="104-1"),linewidth=1) +
  geom_line(aes(y = C5, color="104-1"),linewidth=1) +
  geom_line(aes(y = E5, color="104-1"),linewidth=1) +
  geom_line(aes(y = G5, color="104-1"),linewidth=1) +
  geom_line(aes(y = A7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = C7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = E7, color="104-0.1"),linewidth=1) +
  geom_line(aes(y = G7, color="104-0.1"),linewidth=1) +
  xlim(3,18)+ylim(0,6000000)+
   labs(title="P.ret iLUX Lum/OD",
        x ="Time (hours)", y = "Lum/OD",
         color = "Legend") +
    scale_color_manual(values = colors)
p1
#ggsave("104LO.png")
```